version: "3"
services:
  test:
    image: dawidr/minecraft-docker:4.2.0
    container_name: test_minecraft-docker
    ports:
      - "22222:25565"
    environment:
      - JAVA_VERSION=17.0.4
      - JAVA_IDENTIFIER=tem
      - TYPE=paper
      - MC_VERSION=1.19
      - MEMORY=4096
      - EULA=true
      - DEFAULT_ARGS=true
      - ADDITIONAL_ARGS=
      - FORCE_DOWNLOAD=false
      - JAR_NAME=runme.jar
      - DOWNLOAD_MODS=false
      - MODS=
    stdin_open: true
    tty: true
    volumes:
      - ./test-minecraft-volume:/data:rw
      - ./test-minecraft-volume/sdkman:/sdkman/candidates:rw
    user: 1000:1000
