version: "3"
services:
  test:
    image: dawidr/minecraft-docker:4.0.0
    ports:
      - "25565:25565"
    environment:
      - JAVA_VERSION=17.0.4
      - JAVA_IDENTIFIER=tem
      - TYPE=paper
      - MC_VERSION=1.19
      - MEMORY=4096
      - EULA=false
      - DEFAULT_ARGS=true
      - ADDITIONAL_ARGS=
      - FORCE_DOWNLOAD=false
      - JAR_NAME=runme.jar
    stdin_open: true
    volumes:
      - ./test-minecraft-volume:/data:rw
